name: kinopoisk
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_screenutil: ^5.6.0
  json_serializable: ^6.5.4 
  get: ^4.6.5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/pictures/


  fonts:

  - family: NotoSansSemiBold
    fonts:
      - asset: assets/fonts/NotoSans-SemiBold.ttf

  - family: NotoSansRegular
    fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf
  
  - family: NotoSansMedium
    fonts:
      - asset: assets/fonts/NotoSans-Medium.ttf

